lab_5/urls.py
from django.conf.urls import url
from .views import index, add_todo, delete_todo

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_todo', add_todo, name='add_todo'),
	url(r'^delete_todo/(?P<id>\d+)$', delete_todo, name='delete_todo'),
]

tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import tugas_profile.urls as tugas_profile
import tugas_addfriend.urls as tugas_addfriend
import tugas_updateStatus.urls as tugas_updateStatus
import dashboard.urls as dashboard
from django.views.generic import RedirectView

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^profile/', include(tugas_profile,namespace='tugas_profile')),
	url(r'^friends/', include(tugas_addfriend, namespace='tugas_addfriend')),
	url(r'^stats/', include(dashboard, namespace='dashboard')),
    url(r'^updateStatus/', include(tugas_updateStatus, namespace='tugas_updateStatus')),
    ]

tugas_addfriend/urls.py
from django.conf.urls import url
from .views import index, message_post

urlpatterns = [
			url(r'^$', index, name='index'),
			url(r'^add_friend', message_post, name='add_friend'),
			]

tugas_addfriend/models.py
from django.db import models
import datetime
#import pytz
#from timezone_field import TimeZoneField

# Create your models here.

class Friend(models.Model):
	name = models.CharField(max_length=100)
	url = models.URLField()
	date = models.DateTimeField(auto_now_add=True)

tugas_addfriend/forms.py
from django import forms

class Friend_Form(forms.Form):
	error_messages = {'required' : 'Please fill in the field',
						'invalid' : 'Please fill in the field with the valid URL'}

	attrs = {
    'class': 'form-control-made'
    }

	name = forms.CharField(max_length=100, label='Name', required=True, widget=forms.TextInput(attrs=attrs))
	url = forms.URLField(label='URL', required=True, min_length=14, max_length=100, initial = "https://", 
			widget=forms.URLInput(attrs=attrs))

tugas_addfriend/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

import datetime

# Create your views here.
response = {}

def index(request):
	response['friend_form'] = Friend_Form
	friends = Friend.objects.all()
	response['friend'] = friends
	html = 'tugas_addfriend/tugas_addfriend.html'
	return render(request, html, response)

def message_post(request):
	form = Friend_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		friend = Friend(name=response['name'], url=response['url'])
		friend.save()
		return HttpResponseRedirect('/friends/')
	else:
		return HttpResponseRedirect('/friends/')

tugas_addfriend/templates/tugas_addfriend/tugas_addfriend.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tugas_addfriend.css' %}" />    
    
</head>

    <body style="font-family:monospace; background-color:#2B314C">
    <header>
    {% include "dashboard/partials/header.html" %}
  </header>
    <hr/>
    
    <section name="add_friend" id = "sec1">
      <div class = "container">
        <h2 class="list-friend-title"><b>Add Friend</b></h2>
        <form id="form" method="POST" action="{% url 'tugas_addfriend:add_friend' %}">
            {% csrf_token %}
            {{friend_form}}
            <br>
            <button type="submit" class="btn btn-default">Add Friend</button>
          </form>
        </div>
    </section>

    <section name = "my-friends" id="my-friends">
      <div class="container">
        <h2 class="list-friend-title"><b>List Friend</b></h2>
        <div class="flex">

        {% for i in friend %}

          <div class="flex-item">
            <div class="one-friend">
              <div class="friends-name">
                {{i.name}}
              </div>
              <div class="friends-photo">
                <img src="https://i.imgur.com/0mkAQ84.png" alt="user" width="135" height="135" class="img-circle"/>
              </div>
              <div class="friends-url">
                <a href={{i.url}}>{{i.url}} </a>
              </div>
              <div class="date-added">
                <i> Added {{i.date|date:"j N o H:i:s"}} </i>
              </div>
            </div>
          </div>
        
        {% endfor %}

    </div>
    </div>
    </section>
    </font>
    </body>
    <footer>
    <!-- TODO Block Footer dan include footer.html -->
    {% block footer %}
    {% include "dashboard/partials/footer.html" %}
    {% endblock %}
  </footer>
    </html>