lab_5/urls.py
from django.conf.urls import url
from .views import index, add_todo, delete_todo

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_todo', add_todo, name='add_todo'),
	url(r'^delete_todo/(?P<id>\d+)$', delete_todo, name='delete_todo'),
]

tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import tugas_profile.urls as tugas_profile
import tugas_addfriend.urls as tugas_addfriend
import tugas_updateStatus.urls as tugas_updateStatus
import dashboard.urls as dashboard
from django.views.generic import RedirectView

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^profile/', include(tugas_profile,namespace='tugas_profile')),
	url(r'^friends/', include(tugas_addfriend, namespace='tugas_addfriend')),
	url(r'^stats/', include(dashboard, namespace='dashboard')),
    url(r'^updateStatus/', include(tugas_updateStatus, namespace='tugas_updateStatus')),
    ]

tugas_updateStatus/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status', add_status, name='add_status'),
]

tugas_updateStatus/models.py
from django.db import models

class Status (models.Model):
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

tugas_updateStatus/forms.py
from django import forms

class Status_Form(forms.Form):
	error_messages = {
		'required': 'Tolong isi input ini',
	}
	description_attrs = {
		'type': 'text',
		'cols': 50,
		'rows': 4,
		'class': 'todo-form-textarea',
		'placeholder':'Masukkan status...'
	}

	description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

tugas_updateStatus/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Kelompok 2" #TODO Implement yourname
    status = Status.objects.all()
    response['status'] = status
    html = 'tugas_updateStatus/tugas_updateStatus.html'
    response['status_form'] = Status_Form
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        return HttpResponseRedirect('/updateStatus/')
    else:
        return HttpResponseRedirect('/updateStatus/')

tugas_updateStatus/templates/tugas_updateStatus/tugas_updateStatus.html
{% extends "tugas_updateStatus/layout/base.html" %}
{% block content %}
<style>
.textcol {
    color: white;
    font-size: 24px;
    text-align: center;
}
.textcol2 {
    color: #2B314C;
    font-size: 28px;
    text-align: center;
    text-decoration: bold;
}
textarea {
    resize:none
}

/* animasi colorchange */
@-webkit-keyframes colorchange {
    0% {
        -webkit-text-stroke: 5px #0fb8ad;
    letter-spacing: 0;
    }
  50% {
    -webkit-text-stroke: 7.5px  #1fc8db;
  }
    100% {
        -webkit-text-stroke: 10px  #2cb5e8;
    letter-spacing: 18px;
    }
}
/* styling wrapper form */
#input-list{
  background: linear-gradient(to bottom right, #606062, #393939);
}
/* styling form */
#input-list form{
  width: 400px;
  margin: 50px auto;
  text-align: center;
  position: relative;
  z-index: 1;
  background: #2B314C;
  border: 0 none;
  border-radius: 3px;
  box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);
  padding: 20px 30px;
  box-sizing: border-box;
  position: relative;
}
/* styling judul form, apakah arti dari tanda '>' ? */
#input-list form > h2{
  font-size: 1.3em;
  text-transform: uppercase;
  color: white;
  margin-bottom: 10px;
}
/* styling form input dan textarea, apakah arti dari tanda ',' ? */
#input-list form > .status-form-input, #input-list form > .status-form-textarea{
  padding: 15px;
    border: 1px solid #ccc;
    border-radius: 3px;
    margin-bottom: 10px;
    width: 90%;
    box-sizing: border-box;
    color: #2C3E50;
    font-size: 13px;
}
@media only screen and (max-width: 768px) {
  #input-list form {
      width: 290px;
  }
}

#input-list{
  background: #2B314C;
}
#input-list form{
  width: 100%;
  margin: 10px auto;
  text-align: center;
  position: relative;
  z-index: 1;
  background: white;
  border: 0 none;
  border-radius: 3px;
  box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);
  padding: 20px 30px;
  box-sizing: border-box;
  position: relative;
}
#input-list form:hover{
  -webkit-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
  -moz-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
  -o-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
  box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
  -webkit-transform:translate(0, -5px);
  -moz-transform:translate(0, -5px);
  -o-transform:translate(0, -5px);
  transform:translate(0, -5px);
}
#input-list form > h2{
  font-size: 1.3em;
  text-transform: uppercase;
  color: #2C3E50;
  margin-bottom: 10px;
}
#input-list form > .status-form-input, #input-list form > .status-form-textarea{
  padding: 15px;
    border: 1px solid #ccc;
    border-radius: 3px;
    margin-bottom: 10px;
    width: 100%;
    box-sizing: border-box;
    color: #2C3E50;
    font-size: 13px;
}
#my-status{
  background: #2B314C;
}
.status-list{
  text-align: left;
  padding-top: 5px;
  padding-left: 10px;
  /*ubah ini */
  background: white;
  position: relative;
  z-index: 15;
  margin-bottom: 30px;
  -webkit-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
  -moz-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
  -o-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
  box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
  transition: 0.5s all;
  -webkit-transition: 0.5s all;
  -moz-transition: 0.5s all;
  -o-transition: 0.5s all;
  color: black;
}
.status-list:after{
    content:"";
    display:block;
    height:20px;
    /* ubah ini */
    background:white;
}
.flex{
  display: flex;
  flex-direction: column-reverse;
  flex-wrap: wrap;
  justify-content: flex-start;
  align-items: flex-start;
  align-content: flex-start;
  margin-right: -15px;
  margin-left: -15px;
}
.flex-item{
  padding: 0 0px;
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: 100%;
  width: 100%;
}
.img-circle {
  border-radius: 50%;
  width: 60px;
  height: 60px;
  margin-right: 10px;
}
@media all and (max-width: 768px) {
.flex-item {flex-basis:100%}
}
</style>
<!-- <h1 class="textcol2">Update Status</h1>  -->


<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'tugas_updateStatus:add_status' %}">
            <h2>Type Your Status</h2>
            {% csrf_token %}
            {{ status_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
            <br>
        </form>
    </div>
</section>
<section name="my-status" id="my-status">
    <div class="container">
        <h2 class="textcol">Your Posts</h2>
        <div class="flex">
            {% if status %}
                {% for data in status %}
                    <div class="flex-item">
                        <div class="status-list">
                        <div>
                        <h4><img class="img-circle" src="https://images.8tracks.com/cover/i/009/677/418/Sawada.Tsunayoshi.full.1023723-7467.jpg?rect=0,58,651,651&q=98&fm=jpg&fit=max&w=320&h=320" align="left" alt = "Me">Sawada Tsunayoshi</h4>
                        </div>
                        <div class="status-list-status">
                                {{data.description}}
                            </div>
                        <div class="status-list-date-added">
                                {{data.created_date| date:"d M Y H:i:s"}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada status :v
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}